#!/usr/bin/env bash

declare -r TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %z")"
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

function report_uptime() {
    echo "Function report_uptime executed"
    return
}

function report_disk_space() {
    echo "Function report_disk_space executed"
    return
}

function report_home_space() {
    echo "Function report_home_space executed"
    return
}

cat <<_EOF_
<html>
    <head>
        <title>$TITLE</title>
    </head>
    <body>
        <h1>$TITLE</h1>
        <p>$TIME_STAMP</p>
        $(report_uptime)
        $(report_disk_space)
        $(report_home_space)
    </body>
</html>
_EOF_
