#!/usr/bin/env bash

declare -r TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %z")"
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

function report_uptime() {
    cat <<_EOF_
<h2>System Uptime</h2>
        <pre>$(uptime)</pre>
_EOF_
    return
}

function report_disk_space() {
    cat <<_EOF_
<h2>Disk Space Utilization</h2>
        <pre>$(df -h)</pre>
_EOF_
    return
}

function report_home_space() {
    if [[ $(id -u) -eq 0 ]]; then # if start from root (uid is 0)
        cat <<-EOF
<h2>Home Space Utilization (All Users)</h2>
        <pre>$(du -sh /home/* 2>/dev/null)</pre>
EOF
    else
        cat <<-EOF
<h2>Home Space Utilization ($USER)</h2>
        <pre>$(du -sh "$HOME")</pre>
EOF
    fi
    return
}

cat <<-_EOF_
<html>
    <head>
        <title>$TITLE</title>
    </head>
    <body>
        <h1>$TITLE</h1>
        <p>$TIME_STAMP</p>
        $(report_uptime)
        $(report_disk_space)
        $(report_home_space)
    </body>
</html>
_EOF_
