#!/usr/bin/env bash

decrale -r TITLE="System Information Report for $HOSTNAME"

echo "<html>
    <head>
        <title>$TITLE</title>
    </head>
    <body>
        <h1>$TITLE</h1>
    </body>
</html>"